services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: faktura
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    restart: always
    expose:
      - "8080"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 123456789
      DB_NAME: faktura

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "81:80"
    depends_on:
      - api
    volumes:
      - ./nginx/default.conf:/etc/nginx/nginx.conf:ro

volumes:
  postgres_data:
